language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.5
  - 2.2.0

gemfile:
  - Gemfile
  - gemfiles/Gemfile.rails-3.2.x
  - gemfiles/Gemfile.rails-4.0.x
  - gemfiles/Gemfile.rails-4.1.x

matrix:
  exclude:
    # has test/unit/testcase removed, and also 3.2.x is too old to support
    # ruby 2.2.0. so ignoring this combination.
    - rvm: 2.2.0
      gemfile: gemfiles/Gemfile.rails-3.2.x
    # https://github.com/rspec/rspec-rails/issues/1273
    # waiting for this issue to be resolved
    - rvm: 2.2.0
      gemfile: gemfiles/Gemfile.rails-4.0.x

before_script:
  - RAILS_ENV=test bundle exec rake db:migrate --trace

script:
  - bundle exec rspec spec

# copy hipchat notification settings from rbkit repository
notifications:
  hipchat:
    rooms:
      secure: BXr8nsaTdnOhY9w9pQ4j8CkAxHSIwJr1ANfLsftOs2T9vofJP488qMNb0DLoWI0c3cFpzbzG2enjIqqCuIrHux3s05N9y0fb3s00BNPg+i6iK8+C/VoQd01tuuxYnhjUI3eXnsa65zdJFvO7k04kvPNg/foAnRytArjA1lK8Kss=
    template:
      - '%{result}: %{repository_slug}#%{branch} - <a href="%{compare_url}">%{commit}</a>(%{commit_message}) by %{author} (<a href="%{build_url}">Details</a>)'
    format: html
